sudo: required
language: java
install: true
script: "./gradlew compileDocker"
services:
- docker
notifications:
  slack:
    secure: mv0enf7mUBgARLQclaIRYZ7iG6lOhMgFbWtYMjCCb5fFanPj08c0hxgo7VwIIjJEbNRGLgj2DvsgIfopCaSx0AGmGE+tMBG9uqjF5w8i+cemvOB7GauhTZjF9/mCia9T3C1UlXRMMQwxUkJ9dvVLJNUyjg5LfdpBbcNucfjdALjhZWh3vJQnP1Qz4POuf7qpKYFpOoCdDzI7QydvA+NSTUh36OOi6LAYHpxnPSb4kh1ZpmvKwGB+C4gG8FhH8BEt86lNOoX334ZQQf1Fy5xZ1NnegitYYGEP9XwR8LqWRN8I6lCBPIDmlKjFVNLqudQkFWqiHLh4xyxDU3Y/xF0lY/nDOcIvzNitz3i5WkogyOeycKcm4JzVq7NnhKJyJf99edlBIxD7AeLl/hBp4EdQJ/CeQmAYTvVGv7awgoVINm6b8tiOhxBfHqXNJlIkry5qCzcQwaQkdnRM9ea1a7oQ2fpuoZ3B+WYdHlvcBYc6UL2LPiU6gfM2kM9G/6o+jgcb6xSXKr7WfpCmidSM8mcWoN/onBDbFUT5DSrPJq6y4c55b9rJaeACKBMAPmQ159NXXus7h1c9Vy+rrQrXk5vTHJy2P16Epcnzy1OyDBJH3Ni4DaRZLFL/8SwxyyS3DAopfeAOXHG3J46WBoJ4ri2Nyv7ey9oervqsoXxWMNY+XJc=
